FROM oven/bun:latest AS base

WORKDIR /usr/src/app

COPY package*.json ./

ENV ZONE_ID=ZONE_ID
ENV API_TOKEN=API_TOKEN
ENV CF_GROUP_DOMAIN=sub1.example.com,example.com,sub2.example.com

RUN bun install

# run the app
ENTRYPOINT [ "bun", "run", "index.ts" ]
